server.port: 8181
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring.security.user.name: 'root'
spring.security.user.password=root
spring:
  datasource:
    url: ${DB_RDS}
    username: ${DB_USERNAME_RDS}
    password: ${DB_PASSWORD_RDS}
  jpa:
    hibernate:
      ddl-auto: none